services:
  audio-diarizer:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
      - ./app/templates:/app/app/templates
      - ./app/static:/app/app/static
    environment:
      - PYTHONPATH=/app
      - TEMPLATES_DIR=/app/app/templates
      - STATIC_DIR=/app/app/static
      - DIARIZER_TYPE=lightweight
    restart: unless-stopped